module.exports = {
  docSidebar: [
    {
      type: "category",
      label: "Introduction",
      collapsible: false,
      collapsed: false,
      items: [
        "index",
        {
          type: "category",
          label: "Get started with Swan",
          collapsed: true,
          items: [
            "topics/get-started/step-by-step",
            "topics/get-started/choose-integration",
            "topics/get-started/quickstart",
          ],
        },
        "glossary",
      ],
    },
    {
      type: "category",
      label: "Account onboarding",
      collapsible: false,
      collapsed: false,
      items: [
        {
          type: "category",
          label: "Account onboarding overview",
          link: { type: "doc", id: "topics/onboarding/index" },
          collapsed: true,
          items: [
            "topics/onboarding/overview/guide-get-info",
            "topics/onboarding/overview/guide-get-list",
            "topics/onboarding/overview/guide-export",
            "topics/onboarding/overview/guide-finalize",
          ],
        },
        {
          type: "category",
          label: "Individual accounts",
          link: { type: "doc", id: "topics/onboarding/individual/index" },
          collapsed: true,
          items: [
            "topics/onboarding/individual/guide-create",
            "topics/onboarding/individual/guide-update",
          ],
        },
        {
          type: "category",
          label: "Company accounts",
          link: { type: "doc", id: "topics/onboarding/company/index" },
          collapsed: true,
          items: [
            "topics/onboarding/company/guide-create",
            "topics/onboarding/company/guide-update",
          ],
        },
        {
          type: "category",
          label: "Account holders",
          link: { type: "doc", id: "topics/onboarding/account-holders/index" },
          collapsed: true,
          items: [
            "topics/onboarding/account-holders/guide-add-additional-account",
            "topics/onboarding/account-holders/guide-get-status",
            "topics/onboarding/account-holders/guide-request-first-transfer",
            "topics/onboarding/account-holders/guide-export",
            "topics/onboarding/account-holders/sandbox",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Accounts",
      collapsible: false,
      collapsed: false,
      items: [
        {
          type: "category",
          label: "Accounts overview",
          link: { type: "doc", id: "topics/accounts/index" },
          collapsed: true,
          items: [
            "topics/accounts/overview/guide-generate-statement",
            "topics/accounts/overview/guide-get-bank-details",
            "topics/accounts/overview/guide-export",
          ],
        },
        {
          type: "category",
          label: "Multiple accounts",
          link: { type: "doc", id: "topics/accounts/multiple-accounts/index" },
          collapsed: true,
          items: [
            "topics/accounts/multiple-accounts/guide-multiple-accounts-integration",
          ],
        },
        {
          type: "category",
          label: "Account memberships",
          link: { type: "doc", id: "topics/accounts/memberships/index" },
          collapsed: true,
          items: [
            "topics/accounts/memberships/guide-add-one",
            "topics/accounts/memberships/guide-add-multiple",
            "topics/accounts/memberships/guide-fix-binding-error",
            "topics/accounts/memberships/guide-update",
            "topics/accounts/memberships/guide-suspend-resume",
            "topics/accounts/memberships/guide-disable",
            "topics/accounts/memberships/guide-export",
          ],
        },
        {
          type: "category",
          label: "Supporting documents",
          link: { type: "doc", id: "topics/accounts/documents/index" },
          collapsed: true,
          items: [
            "topics/accounts/documents/guide-upload-onboarding",
            "topics/accounts/documents/guide-upload-transaction",
            "topics/accounts/documents/guide-get-info",
            "topics/accounts/documents/guide-request-collection-review",
            "topics/accounts/documents/guide-delete",
            "topics/accounts/documents/sandbox",
          ],
        },
        {
          type: "category",
          label: "Account funding",
          link: { type: "doc", id: "topics/accounts/funding/index" },
          collapsed: true,
          items: [
            "topics/accounts/funding/guide-add-source",
            "topics/accounts/funding/guide-initiate-request",
            "topics/accounts/funding/guide-cancel-source",
            "topics/accounts/funding/guide-get-info",
            "topics/accounts/funding/sandbox",
          ],
        },
        {
          type: "category",
          label: "Closing accounts",
          link: { type: "doc", id: "topics/accounts/closure/index" },
          collapsed: true,
          items: [
            "topics/accounts/closure/guide-close-link",
            "topics/accounts/closure/guide-close-api",
            "topics/accounts/closure/guide-close-limited",
            "topics/accounts/closure/guide-close-unlimited",
          ],
        },
        {
          type: "category",
          label: "Billing",
          link: { type: "doc", id: "topics/accounts/billing/index" },
          collapsed: true,
          items: [
            "topics/accounts/billing/guide-compliant-billing",
            "topics/accounts/billing/guide-get-list",
            "topics/accounts/billing/guide-get-details",
            "topics/accounts/billing/sandbox",
          ],
        },
        {
          type: "category",
          label: "IBANs",
          link: { type: "doc", id: "topics/accounts/ibans/index" },
          collapsed: true,
          items: [
            "topics/accounts/ibans/guide-validate",
            "topics/accounts/ibans/guide-add-virtual",
            "topics/accounts/ibans/guide-cancel-virtual",
            "topics/accounts/ibans/guide-get-info",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Capital deposits",
      collapsible: false,
      collapsed: false,
      items: [
        {
          type: "category",
          label: "Capital deposits",
          link: { type: "doc", id: "topics/capital-deposits/index" },
          collapsed: true,
          items: [
            "topics/capital-deposits/guide-cancel",
          ],
        },
        {
          type: "category",
          label: "🇫🇷 France",
          link: { type: "doc", id: "topics/capital-deposits/france/guide" },
          collapsed: true,
          items: [
            "topics/capital-deposits/france/guide-create-case",
            "topics/capital-deposits/france/guide-upload-documents",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Cards",
      collapsible: false,
      collapsed: false,
      items: [
        {
          type: "category",
          label: "Cards overview",
          link: { type: "doc", id: "topics/cards/index" },
          collapsed: true,
          items: [
            "topics/cards/overview/guide-issue",
            "topics/cards/overview/guide-update",
            "topics/cards/overview/guide-export",
          ],
        },
        {
          type: "category",
          label: "Card design",
          link: { type: "doc", id: "topics/cards/design/index" },
          collapsed: true,
          items: [
            "topics/cards/design/guide-standard",
            "topics/cards/design/guide-custom",
          ],
        },
        {
          type: "category",
          label: "Virtual cards",
          link: { type: "doc", id: "topics/cards/virtual/index" },
          collapsed: true,
          items: [
            "topics/cards/virtual/guide-add",
            "topics/cards/virtual/guide-view-info",
            "topics/cards/virtual/guide-cancel",
          ],
        },
        {
          type: "category",
          label: "Physical cards",
          link: { type: "doc", id: "topics/cards/physical/index" },
          collapsed: true,
          items: [
            "topics/cards/physical/guide-print",
            "topics/cards/physical/guide-activate",
            "topics/cards/physical/guide-view-info",
            "topics/cards/physical/guide-block-unblock",
            "topics/cards/physical/guide-renew",
            "topics/cards/physical/guide-cancel",
            "topics/cards/physical/sandbox",
          ],
        },
        {
          type: "category",
          label: "Digital cards",
          link: { type: "doc", id: "topics/cards/digital/index" },
          collapsed: true,
          items: [
            "topics/cards/digital/guide-add",
            "topics/cards/digital/guide-cancel",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Merchants",
      collapsible: false,
      collapsed: false,
      items: [
        {
          type: "category",
          label: "Merchants overview",
          link: { type: "doc", id: "topics/merchants/index" },
          collapsed: true,
          items: [
            "topics/merchants/guide-onboarding-overview",
            "topics/merchants/guide-missing-information",
            "topics/merchants/profiles/guide-request",
            "topics/merchants/profiles/guide-update",
            "topics/merchants/profiles/guide-get-info",
            "topics/merchants/sandbox",
          ],
        },
        {
          type: "category",
          label: "Accepting online payments",
          link: { type: "doc", id: "topics/merchants/online/index" },
          collapsed: true,
          items: [
            {
              type: "category",
              label: "Cards",
              link: { type: "doc", id: "topics/merchants/online/cards/index" },
              collapsed: true,
              items: [
                "topics/merchants/online/cards/guide-cards",
                "topics/merchants/online/cards/guide-request",
                "topics/merchants/online/cards/guide-create-link",
                "topics/merchants/online/cards/sandbox",
              ],
            },
            {
              type: "category",
              label: "SEPA Direct Debit",
              link: { type: "doc", id: "topics/merchants/online/sdd/index" },
              collapsed: true,
              items: [
                "topics/merchants/online/sdd/guide-sdd",
                "topics/merchants/online/sdd/guide-request",
                "topics/merchants/online/sdd/guide-declare",
                "topics/merchants/online/sdd/guide-initiate",
                "topics/merchants/online/sdd/guide-update",
                "topics/merchants/online/sdd/guide-create-link",
                "topics/merchants/online/sdd/sandbox",
              ],
            },
            {
              type: "category",
              label: "Internal Direct Debit",
              link: { type: "doc", id: "topics/merchants/online/idd/index" },
              collapsed: true,
              items: [
                "topics/merchants/online/idd/guide-idd",
                "topics/merchants/online/idd/guide-request",
                "topics/merchants/online/idd/guide-declare",
                "topics/merchants/online/idd/guide-initiate",
                "topics/merchants/online/idd/guide-refund",
                "topics/merchants/online/idd/sandbox",
              ],
            },
            {
              type: "category",
              label: "French checks",
              link: { type: "doc", id: "topics/merchants/online/checks/index" },
              collapsed: true,
              items: [
                "topics/merchants/online/checks/guide-checks",
                "topics/merchants/online/checks/guide-request",
                "topics/merchants/online/checks/guide-initiate",
                "topics/merchants/online/checks/sandbox",
              ],
            },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Payments",
      collapsible: false,
      collapsed: false,
      items: [
        {
          type: "category",
          label: "Payments overview",
          link: { type: "doc", id: "topics/payments/index" },
          collapsed: true,
          items: [
            "topics/payments/overview/guide-get-payment-info",
            "topics/payments/overview/guide-get-payment-id",
            "topics/payments/overview/guide-get-transaction-info",
            "topics/payments/overview/guide-get-transaction-id",
            "topics/payments/overview/guide-get-transaction-list",
            "topics/payments/overview/guide-generate-transaction-statement",
            "topics/payments/overview/guide-export",
          ],
        },
        {
          type: "category",
          label: "Card payments",
          link: { type: "doc", id: "topics/payments/cards/index" },
          collapsed: true,
          items: [
            "topics/payments/cards/guide-get-list",
            "topics/payments/cards/guide-get-enriched-info",
            "topics/payments/cards/sandbox",
          ],
        },
        {
          type: "category",
          label: "Credit transfers",
          link: { type: "doc", id: "topics/payments/credit-transfers/index" },
          collapsed: true,
          items: [
            {
              type: "category",
              label: "SEPA Credit Transfers",
              link: {
                type: "doc",
                id: "topics/payments/credit-transfers/sepa/index",
              },
              collapsed: true,
              items: [
                "topics/payments/credit-transfers/sepa/guide-initiate-ct",
                "topics/payments/credit-transfers/sepa/guide-cancel-ct",
                "topics/payments/credit-transfers/sepa/guide-refund-ct",
                {
                  type: "category",
                  label: "Verification of Payee (VoP)",
                  link: { type: "doc", id: "topics/payments/credit-transfers/sepa/vop/verification-of-payee" },
                  collapsed: true,
                  items: [
                    'topics/payments/credit-transfers/sepa/vop/guide-verify-beneficiary',
                    'topics/payments/credit-transfers/sepa/vop/bulk-credit-transfers',
                    'topics/payments/credit-transfers/sepa/vop/incoming-vop-requests',
                  ],
                },
                "topics/payments/credit-transfers/sepa/guide-verify-beneficiary",
                "topics/payments/credit-transfers/sepa/guide-add-beneficiary",
                "topics/payments/credit-transfers/sepa/guide-schedule-so",
                "topics/payments/credit-transfers/sepa/guide-cancel-so",
                "topics/payments/credit-transfers/sepa/sandbox",
              ],
            },
            {
              type: "category",
              label: "International Credit Transfers",
              link: {
                type: "doc",
                id: "topics/payments/credit-transfers/international/index",
              },
              collapsed: true,
              items: [
                "topics/payments/credit-transfers/international/guide-quote",
                "topics/payments/credit-transfers/international/guide-beneficiary",
                "topics/payments/credit-transfers/international/guide-transaction-details",
                "topics/payments/credit-transfers/international/guide-initiate",
                "topics/payments/credit-transfers/international/guide-add-beneficiary",
                "topics/payments/credit-transfers/international/guide-get-info",
                "topics/payments/credit-transfers/international/sandbox",
              ],
            },
          ],
        },
        {
          type: "category",
          label: "Direct debit",
          link: { type: "doc", id: "topics/payments/direct-debit/index" },
          collapsed: true,
          items: [
            "topics/payments/direct-debit/guide-return",
            "topics/payments/direct-debit/guide-add-mandate",
            "topics/payments/direct-debit/guide-update-mandate",
            "topics/payments/direct-debit/guide-suspend-mandate",
            "topics/payments/direct-debit/guide-enable-mandate",
            "topics/payments/direct-debit/sandbox",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Projects",
      collapsible: false,
      collapsed: false,
      items: [
        {
          type: "category",
          label: "Projects overview",
          link: { type: "doc", id: "topics/projects/index" },
          collapsed: true,
          items: ["topics/projects/guide-activate"],
        },
      ],
    },
    {
      type: "category",
      label: "Users",
      collapsible: false,
      collapsed: false,
      items: [
        {
          type: "category",
          label: "Users overview",
          link: { type: "doc", id: "topics/users/index" },
          collapsed: true,
          items: [
            "topics/users/overview/guide-get-list",
            "topics/users/overview/guide-get-info-multiple",
            "topics/users/overview/guide-get-info-one",
            "topics/users/overview/guide-export",
            "topics/users/overview/guide-deactivate",
          ],
        },
        {
          type: "category",
          label: "Consent",
          link: { type: "doc", id: "topics/users/consent/index" },
          collapsed: true,
          items: [
            "topics/users/consent/guide-configure-notifications",
            "topics/users/consent/guide-create-multiconsent",
            "topics/users/consent/guide-implement-s2s",
            "topics/users/consent/guide-integrate-sca",
          ],
        },
        {
          type: "category",
          label: "Identifications",
          link: { type: "doc", id: "topics/users/identifications/index" },
          collapsed: true,
          items: [
            "topics/users/identifications/guide-get-identifications",
            "topics/users/identifications/guide-get-latest-id",
            "topics/users/identifications/sandbox",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Resources",
      collapsible: false,
      collapsed: false,
      items: [
        {
          type: "link",
          label: "Status page",
          href: "https://status.swan.io/",
        },
        {
          type: "link",
          label: "Trust Center",
          href: "https://trust.swan.io/",
        },
        {
          type: "link",
          label: "Support Center",
          href: "https://support.swan.io/hc/en-150",
        },
        {
          type: "link",
          label: "Roadmap",
          href: "https://swanio.notion.site/Swan-Public-Roadmap-385e4b2e91b3409786a6c8e885654a22",
        },
        "topics/contact",
      ],
    },
  ],
  partnershipSidebar: [
    {
      type: "category",
      label: "Overview",
      collapsible: false,
      collapsed: false,
      items: [
        {
          type: "category",
          label: "Partnership with Swan",
          link: { type: "doc", id: "partnership/index" },
          collapsed: true,
          items: ["partnership/overview/guide-orias"],
        },
        "partnership/overview/rules-regulations",
        "partnership/overview/country-coverage",
      ],
    },
    {
      type: "category",
      label: "Protections",
      collapsible: false,
      collapsed: false,
      items: [
        "partnership/protections/financial",
        {
          type: "category",
          label: "Fraud protection",
          link: { type: "doc", id: "partnership/protections/fraud/index" },
          collapsed: true,
          items: ["partnership/protections/fraud/types"],
        },
        "partnership/protections/data",
        "partnership/protections/report-vulnerability",
      ],
    },
    {
      type: "category",
      label: "Document center",
      collapsible: false,
      collapsed: false,
      items: [
        {
          type: "category",
          label: "Proof of company registration",
          link: { type: "doc", id: "partnership/document-center/company-registration/index" },
          collapsed: true,
          items: [
            "partnership/document-center/company-registration/france",
            "partnership/document-center/company-registration/germany",
            "partnership/document-center/company-registration/italy",
            "partnership/document-center/company-registration/netherlands",
            "partnership/document-center/company-registration/spain",
          ],
        },
        "partnership/document-center/proof-address/index",
        {
          type: "category",
          label: "Identity documents",
          link: { type: "doc", id: "partnership/document-center/identity/index" },
          collapsed: true,
          items: [
            "partnership/document-center/identity/expert",
            "partnership/document-center/identity/pvid",
            "partnership/document-center/identity/qes",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Resources",
      collapsible: false,
      collapsed: false,
      items: [
        {
          type: "link",
          label: "Status page",
          href: "https://status.swan.io/",
        },
        {
          type: "link",
          label: "Trust Center",
          href: "https://trust.swan.io/",
        },
        {
          type: "link",
          label: "Support Center",
          href: "https://support.swan.io/hc/en-150",
        },
        {
          type: "link",
          label: "Roadmap",
          href: "https://swanio.notion.site/Swan-Public-Roadmap-385e4b2e91b3409786a6c8e885654a22",
        },
        "partnership/contact",
      ],
    },
  ],
  developersSidebar: [
    {
      type: "category",
      label: "Overview",
      collapsible: false,
      collapsed: false,
      items: [
        "developers/index",
        "developers/graphql",
        {
          type: "link",
          label: "API Explorer",
          href: "https://explorer.swan.io/",
        },
        {
          type: "link",
          label: "API Reference",
          href: "https://api-reference.swan.io/",
          customProps: {
            target: "_self",
          },
        },
      ],
    },
    {
      type: "category",
      label: "Tools",
      collapsible: false,
      collapsed: false,
      items: [
        {
          type: "category",
          label: "Tools overview",
          link: { type: "doc", id: "developers/tools/index" },
          collapsed: true,
          items: [
            "developers/tools/api-explorer",
            "developers/tools/testing-api",
            "developers/tools/event-simulator",
            "developers/tools/sandbox-users",
            "developers/tools/postman-collection",
          ],
        },
        "developers/tools/guide-test-tools",
      ],
    },
    {
      type: "category",
      label: "Using the API",
      collapsible: false,
      collapsed: false,
      items: [
        {
          type: "category",
          label: "Authentication",
          link: {
            type: "doc",
            id: "developers/using-api/authentication/index",
          },
          collapsed: true,
          items: [
            "developers/using-api/authentication/guide-get-token-user",
            "developers/using-api/authentication/guide-get-token-project",
            "developers/using-api/authentication/guide-impersonate",
          ],
        },
        "developers/using-api/errors-rejections",
        "developers/using-api/pagination",
        "developers/using-api/payment-control",
        "developers/using-api/webhooks",
        "developers/using-api/idempotency",
      ],
    },
    {
      type: "category",
      label: "Open Source",
      collapsible: false,
      collapsed: false,
      items: [
        {
          type: "link",
          label: "Swan Banking Frontend",
          href: "https://swan-io.github.io/swan-partner-frontend/",
        },
      ],
    },
    {
      type: "category",
      label: "Resources",
      collapsible: false,
      collapsed: false,
      items: [
        {
          type: "link",
          label: "Status page",
          href: "https://status.swan.io/",
        },
        {
          type: "link",
          label: "Trust Center",
          href: "https://trust.swan.io/",
        },
        {
          type: "link",
          label: "Support Center",
          href: "https://support.swan.io/hc/en-150",
        },
        {
          type: "link",
          label: "Roadmap",
          href: "https://swanio.notion.site/Swan-Public-Roadmap-385e4b2e91b3409786a6c8e885654a22",
        },
        "developers/contact",
      ],
    },
  ],
  previewSidebar: [
    {
      type: 'doc',
      id: 'preview/index',
      label: 'Upcoming features',
      className: 'sidebar-preview-notice',
    },
    'preview/belgian-ibans',
    // Add more preview features here
    {
      type: "category",
      label: "Beta",
      collapsible: false,
      collapsed: false,
      items: [
        {
          type: "category",
          label: "Card insurance",
          link: { type: "doc", id: "preview/card-insurance/card-insurance" },
          collapsed: true,
          items: [
            "preview/card-insurance/guide-insurance-integration",
          ],
        },
        // Add more preview features here
      ],
    },
  ],
};
